# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movies
  pod 'R.swift'
  pod 'SDWebImage'
  pod 'Cosmos', '~> 22.1'
  pod 'Alamofire', '~> 5.2'  
  target 'moviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moviesUITests' do
    # Pods for testing
  end

end
